### ISSUE TITLE
View and DOM are out of sync

### ISSUE THREAD

**Issue by inca** [lucthev/compose#79]
OK, I'm quite unsure on where should I post silly questions like this one... so please forgive my persistence :)

I am actually trying to get Compose working with Angular in a pretty basic startup (with plans to work on some plugins later). Right now I am stuck because I'm getting this `View and DOM are out of sync` errors which prevent me from moving anywhere else.

Just in case you are not deep with Angular internals, I'll explain some key points:

  * it maintains its own event lifecycle (and much more), so when the content is updated in the editor, it needs to be notified about the changes;
  * right now I am using the `input` event so that I can react on every keystroke;
  * Angular is also famous for its "two-way binding" thing where data (in this case HTML content) from the controller must be pushed back to the editor; I do this by simply setting the `innerHTML` on the element, but I suspect that I must also notify the editor about that somehow...

Could you please give me a clue on how to replace the contents of the editor dynamically?

**Comment by inca** [comment]
Here's the relevant piece of code (note that the function describes an Angular directive):

```
module.exports = function() {

  var Compose = require('compose-editor');

  return {
    restrict: 'A',
    require: 'ngModel',
    link: function($scope, $element, $attrs, ngModel) {

      var editor = new Compose($element[0]);

      function onInput(ev) {
        var html = $element.html();
        ngModel.$setViewValue(html);
      }

      $element.on('input', onInput);

      $element.on('$destroy', function() {
        $element.off('input', onInput);
      });

      ngModel.$render = function() {
        $element.html(ngModel.$viewValue || '');
      };

      $scope.$watch($attrs.ngModel, function(value) {
        var view = editor.plugins.view;
        // Here we must update editor's elements...
      });

    }
  }

};
```

**Comment by lucthev** [comment]
Compose is “some assembly required” at the moment — it doesn’t really do much out of the box. Compose’s abstract representation of the DOM has to be [manually initialised][init], and the behaviour of the enter, backspace, paste, cut, type-over (when the user selected multiple paragraphs and overwrites them by entering text) and other events have to be defined. I plan on adding some kind of `init` method that does the setup automatically, and eventually create a “Rich text mode” plugin that does all of the above with sane defaults; in the meantime, there’s still a lot of work involved simply to get a functional editor.

The “View and DOM are out of sync error” that you’re getting is [thrown][err] when there is a mismatch between the number of paragraphs in the View’s abstract representation of the DOM, and the number of paragraphs in the DOM itself; this probably happens when you set the `innerHTML` of the element.

I’ll try uploading a bare-bones editor setup within the next few days, and perhaps some rough API docs; sorry if usage isn’t very clear right now.

[init]: https://github.com/lucthev/compose/blob/f7e3edbe58d72060bc9c53d7efdf147c02b5ae33/test/unit/delta.spec.js#L1499-L1513
[err]: https://github.com/lucthev/compose/blob/99e46ebe89e5963697a1dc2f88ab93cdafbe70c5/src/view.js#L243

**Comment by inca** [comment]
Thanks for your thorough explanations, I've figured that views must be initialized manually by looking at the tests.

I strongly agree on the intent to make "fat-free" functional editor API first; stuff like toolbars, popups and textarea syncs should be optional and available as separate npm modules. However, almost every usage/integration scenario which I can come up with require editor to expose at least `setHtml` which initializes editor with initial content and `onChange` event (edit intent) so that we could "communicate" to it.

So, I'm closing this one right now; wish you tons of luck and looking forward for more stable API :)
